#!/bin/bash

protoc \
--proto_path=$GOPATH/src/github.com/nathanows/elegant-monolith/_protos \
-I=$GOPATH/src \
-I=$GOPATH/src/github.com/gogo/protobuf/protobuf \
--gogo_out=Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,\
Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,\
plugins=grpc:\
$GOPATH/src/github.com/nathanows/elegant-monolith/_protos $GOPATH/src/github.com/nathanows/elegant-monolith/_protos/code/code.proto
